# CMake toolchain file for Nintendo 64 (libdragon)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION "0.0.0")
set(CMAKE_SYSTEM_PROCESSOR mips)

if(DEFINED ENV{N64_INST})
    set(N64_INST $ENV{N64_INST})
else()
    set(N64_INST /usr)
endif()

set(N64_TARGET mips64-elf)
set(TOOLCHAIN_PREFIX_PATH ${N64_INST}/bin/${N64_TARGET})

set(CMAKE_C_COMPILER   "${TOOLCHAIN_PREFIX_PATH}-gcc" CACHE STRING "C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX_PATH}-g++" CACHE STRING "C++ compiler" FORCE)

set(CMAKE_C_FLAGS_INIT "")
set(CMAKE_CXX_FLAGS_INIT ${CMAKE_C_FLAGS_INIT})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(PLAT_N64 TRUE)

message(STATUS "Nintendo 64 MIPS64 toolchain invoked")
